//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectABI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Contact
    {
        public string adresseContact { get; set; }
        public string commentairesContact { get; set; }
        public string telephoneContact { get; set; }
        public string nomContact { get; set; }
        public int idClient { get; set; }
    
        public virtual Table_Client Table_Client { get; set; }
    }
}
